//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_default p__default;
        
        private static SteamVR_Input_ActionSet_VizNavigation p_VizNavigation;
        
        private static SteamVR_Input_ActionSet_MenuInteraction p_MenuInteraction;
        
        private static SteamVR_Input_ActionSet_Testing p_Testing;
        
        public static SteamVR_Input_ActionSet_default _default
        {
            get
            {
                return SteamVR_Actions.p__default.GetCopy<SteamVR_Input_ActionSet_default>();
            }
        }
        
        public static SteamVR_Input_ActionSet_VizNavigation VizNavigation
        {
            get
            {
                return SteamVR_Actions.p_VizNavigation.GetCopy<SteamVR_Input_ActionSet_VizNavigation>();
            }
        }
        
        public static SteamVR_Input_ActionSet_MenuInteraction MenuInteraction
        {
            get
            {
                return SteamVR_Actions.p_MenuInteraction.GetCopy<SteamVR_Input_ActionSet_MenuInteraction>();
            }
        }
        
        public static SteamVR_Input_ActionSet_Testing Testing
        {
            get
            {
                return SteamVR_Actions.p_Testing.GetCopy<SteamVR_Input_ActionSet_Testing>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p__default = ((SteamVR_Input_ActionSet_default)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_default>("/actions/default")));
            SteamVR_Actions.p_VizNavigation = ((SteamVR_Input_ActionSet_VizNavigation)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_VizNavigation>("/actions/VizNavigation")));
            SteamVR_Actions.p_MenuInteraction = ((SteamVR_Input_ActionSet_MenuInteraction)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_MenuInteraction>("/actions/MenuInteraction")));
            SteamVR_Actions.p_Testing = ((SteamVR_Input_ActionSet_Testing)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_Testing>("/actions/Testing")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions._default,
                    SteamVR_Actions.VizNavigation,
                    SteamVR_Actions.MenuInteraction,
                    SteamVR_Actions.Testing};
        }
    }
}
