//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_default p__default;
        
        private static SteamVR_Input_ActionSet_CellNavigation p_CellNavigation;
        
        private static SteamVR_Input_ActionSet_TestActions p_TestActions;
        
        public static SteamVR_Input_ActionSet_default _default
        {
            get
            {
                return SteamVR_Actions.p__default.GetCopy<SteamVR_Input_ActionSet_default>();
            }
        }
        
        public static SteamVR_Input_ActionSet_CellNavigation CellNavigation
        {
            get
            {
                return SteamVR_Actions.p_CellNavigation.GetCopy<SteamVR_Input_ActionSet_CellNavigation>();
            }
        }
        
        public static SteamVR_Input_ActionSet_TestActions TestActions
        {
            get
            {
                return SteamVR_Actions.p_TestActions.GetCopy<SteamVR_Input_ActionSet_TestActions>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p__default = ((SteamVR_Input_ActionSet_default)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_default>("/actions/default")));
            SteamVR_Actions.p_CellNavigation = ((SteamVR_Input_ActionSet_CellNavigation)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_CellNavigation>("/actions/CellNavigation")));
            SteamVR_Actions.p_TestActions = ((SteamVR_Input_ActionSet_TestActions)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_TestActions>("/actions/TestActions")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions._default,
                    SteamVR_Actions.CellNavigation,
                    SteamVR_Actions.TestActions};
        }
    }
}
