//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_VizNavigation : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Position
        {
            get
            {
                return SteamVR_Actions.vizNavigation_Position;
            }
        }
        
        public virtual SteamVR_Action_Boolean Rotation
        {
            get
            {
                return SteamVR_Actions.vizNavigation_Rotation;
            }
        }
        
        public virtual SteamVR_Action_Boolean Scale
        {
            get
            {
                return SteamVR_Actions.vizNavigation_Scale;
            }
        }
    }
}
