//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_Timeline : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Select
        {
            get
            {
                return SteamVR_Actions.timeline_Select;
            }
        }
        
        public virtual SteamVR_Action_Boolean Scroll
        {
            get
            {
                return SteamVR_Actions.timeline_Scroll;
            }
        }
        
        public virtual SteamVR_Action_Boolean Back
        {
            get
            {
                return SteamVR_Actions.timeline_Back;
            }
        }
    }
}
